#!/usr/bin/python3

"""

APP: Inquisition
DESC: Alert.py - a class representing an alert and its metadata
CREATION_DATE: 2017-10-16

"""

# MODULES
# | Native

# | Third-Party

# | Custom

# METADATA
__author__ = 'Joshua Carlson-Purcell'
__copyright__ = 'Copyright 2017, CarlsoNet'
__license__ = 'MIT'
__version__ = '1.0.0-alpha'
__maintainer__ = 'Joshua Carlson-Purcell'
__email__ = 'jcarlson@carlso.net'
__status__ = 'Development|Staging|Production'


class Alert():
    """
    Alert object, usually generated by one of Inquisition's detection engines

    TIMESTAMP: timestamp the alert was created
    ALERT_TYPE: type of alert: 0 = anomaly, 1 = threat
    ALERT_TYPE: type of alert: 0 = anomaly, 1 = threat
    STATUS: status of the alert: 0 = NEW, 1 = ACKNOWLEDGED, 2 = RESOLVED
    """

    timestamp = 0
    alertType = 0
    status = 0
    logData = {}

    def __init__(self, logData, timestamp=0, alertType=0, status=0):
        # set metadata
        self.timestamp = timestamp
        self.alertType = alertType
        self.status = status
        self.logData = logData


    def __str__(self):
        """
        toString function for printing alert info

        :return: str
        """

        return '[ TIMESTAMP: ' + str(self.timestamp) + ' // TYPE: ' + str(self.alertType) + ' // STATUS: ' + str(self.status) + ' // LOG DATA: { ' + str(self.logData) + ' }]'

